import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaPalette, FaTimes, FaCheck } from 'react-icons/fa';
import { useTheme, THEMES } from '../context/ThemeContext';

export default function ThemeSelector() {
  const [isOpen, setIsOpen] = useState(false);
  const { currentTheme, changeTheme } = useTheme();
  return (<>
    <motion.button whileHover={{ scale: 1.1, rotate: 15 }} whileTap={{ scale: 0.9 }} onClick={() => setIsOpen(true)} className="fixed bottom-32 md:bottom-6 right-6 z-40 w-14 h-14 rounded-full bg-gradient-to-br from-purple-600 to-pink-600 border-2 border-purple-400/50 shadow-lg shadow-purple-500/50 flex items-center justify-center"><FaPalette className="text-white text-xl" /></motion.button>
    <AnimatePresence>{isOpen && (<><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setIsOpen(false)} className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50" /><motion.div initial={{ opacity: 0, scale: 0.8, y: 50 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.8, y: 50 }} className="fixed inset-0 z-50 flex items-center justify-center p-4 pointer-events-none"><div className="glass-effect rounded-2xl p-6 max-w-2xl w-full border-2 border-cyan-500/50 shadow-2xl shadow-cyan-500/30 pointer-events-auto"><div className="flex items-center justify-between mb-6"><h2 className="text-2xl font-bold gradient-text">CHOOSE THEME</h2><button onClick={() => setIsOpen(false)} className="w-10 h-10 rounded-full bg-red-500/20 border border-red-400/50 flex items-center justify-center hover:bg-red-500/40"><FaTimes className="text-red-400" /></button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{Object.values(THEMES).map((theme) => (<motion.button key={theme.id} whileHover={{ scale: 1.05, y: -5 }} whileTap={{ scale: 0.95 }} onClick={() => { changeTheme(theme.id); setIsOpen(false); }} className={`group relative rounded-xl overflow-hidden border-2 transition-all ${currentTheme === theme.id ? 'border-cyan-400 shadow-lg shadow-cyan-500/50' : 'border-gray-700 hover:border-cyan-500/50'}`}><div className="w-full h-24 relative" style={{ background: theme.bg, backgroundImage: `linear-gradient(${theme.gridColor} 1px, transparent 1px), linear-gradient(90deg, ${theme.gridColor} 1px, transparent 1px)`, backgroundSize: '20px 20px' }}><div className="absolute inset-0 flex items-center justify-center text-4xl">{theme.icon}</div></div><div className="p-3 bg-black/60 backdrop-blur-sm"><p className="text-sm font-bold text-white text-center">{theme.name.toUpperCase()}</p><p className="text-[10px] text-gray-400 text-center">{theme.description}</p></div>{currentTheme === theme.id && <div className="absolute top-2 right-2 w-6 h-6 rounded-full bg-cyan-400 flex items-center justify-center"><FaCheck className="text-black text-xs" /></div>}</motion.button>))}</div></div></motion.div></>)}</AnimatePresence>
  </>);
}
